# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

run:
  timeout: 3m

issues:
  max-issues-per-linter: 10
  max-same-issues: 10

linters-settings:
  gocritic:
    enabled-checks:
      - captLocal
      - dupImport
      - singleCaseSwitch
    disabled-checks:
      - appendAssign
    enabled-tags:
      - diagnostic
    disabled-tags:
      - performance
      - style
      - experimental
      - opinionated
  stylecheck:
    checks: ["-ST1000", "-ST1003", "-ST1020", "-ST1021", "-ST1022"]
  goheader:
    template: |-
      Copyright (c) Abstract Machines
      SPDX-License-Identifier: Apache-2.0
  unparam:
    check-exported: true
  unused:
    field-writes-are-uses: false
    generated-is-used: false
  wrapcheck:
    ignoreSigRegexps:
      - "github.com/absmach/magistrala-ui/ui.Service"
    ignorePackageGlobs:
      - "net/http"
      - "database/sql"
      - "encoding/json"
      - "golang.org/x/sync/errgroup"

linters:
  disable-all: true
  enable:
    - gocritic
    - gosimple
    - errcheck
    - govet
    - unused
    - goconst
    - godot
    - ineffassign
    - misspell
    - stylecheck
    - whitespace
    - gci
    - gofmt
    - goimports
    - loggercheck
    - goheader
    - asasalint
    - asciicheck
    - bidichk
    - contextcheck
    - decorder
    - dogsled
    - errchkjson
    - errname
    - execinquery
    - exportloopref
    - ginkgolinter
    - gocheckcompilerdirectives
    - gofumpt
    - goprintffuncname
    - importas
    - makezero
    - mirror
    - nakedret
    - dupword
    - revive
    - nilerr
    - unconvert
    - unparam
    - usestdlibvars
    - wrapcheck
